// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMConsulting.DAL.Context;

#nullable disable

namespace SMConsulting.DAL.Migrations
{
    [DbContext(typeof(SmDbContext))]
    partial class SmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMConsulting.Core.Entities.About", b =>
                {
                    b.Property<int>("AboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutId"));

                    b.Property<DateTime>("AboutCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AboutDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutId");

                    b.HasIndex("AboutId");

                    b.ToTable("Abouts1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Applyment", b =>
                {
                    b.Property<int>("AppylmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppylmentId"));

                    b.Property<string>("ApplymentCompany")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ApplymentCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApplymentEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ApplymentMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ApplymentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ApplymentPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ApplymentPosition")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("AppylmentId");

                    b.HasIndex("AppylmentId");

                    b.ToTable("Applyments1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"));

                    b.Property<DateTime>("BlogCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("BlogMainContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogMainImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogSecondaryImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogSubcontent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogId");

                    b.HasIndex("BlogId");

                    b.ToTable("Blogs1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<DateTime>("CardCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CardDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardId");

                    b.HasIndex("CardId");

                    b.ToTable("Cards1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.CardSpecification", b =>
                {
                    b.Property<int>("CardSpecificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardSpecificationId"));

                    b.Property<DateTime>("CardSpecificationCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CardSpecificationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardSpecificationIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardSpecificationTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardSpecificationId");

                    b.HasIndex("CardSpecificationId");

                    b.ToTable("CardSpecifications1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("ContactAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ContactCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ContactId");

                    b.HasIndex("ContactId");

                    b.ToTable("Contacts1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Difficulty", b =>
                {
                    b.Property<int>("DifficultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DifficultyId"));

                    b.Property<int>("DifficultSectorHelpId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DifficultyCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DifficultyDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DifficultyId");

                    b.HasIndex("DifficultSectorHelpId");

                    b.ToTable("Difficulties1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Hero", b =>
                {
                    b.Property<int>("HeroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeroId"));

                    b.Property<DateTime>("HeroCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeroDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HeroId");

                    b.HasIndex("HeroId");

                    b.ToTable("Heros1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<DateTime>("MemberCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("Members1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartnerId"));

                    b.Property<DateTime>("PartnerCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartnerDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerWebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartnerId");

                    b.HasIndex("PartnerId");

                    b.ToTable("Partners1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("RefreshTokenCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RefreshTokenExpireTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RefreshTokenIsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RefreshTokenToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RefreshTokenUserId")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("RefreshTokenToken")
                        .IsUnique();

                    b.HasIndex("RefreshTokenUserId");

                    b.ToTable("RefreshTokens1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Sector", b =>
                {
                    b.Property<int>("SectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectorId"));

                    b.Property<DateTime>("SectorCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SectorDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectorId");

                    b.HasIndex("SectorId");

                    b.ToTable("Sectors1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.SectorHelp", b =>
                {
                    b.Property<int>("SectorHelpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectorHelpId"));

                    b.Property<DateTime>("SectorHelpCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SectorHelpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectorHelpSectorId")
                        .HasColumnType("int");

                    b.HasKey("SectorHelpId");

                    b.HasIndex("SectorHelpSectorId");

                    b.ToTable("SectorHelps1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<DateTime>("ServiceCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceFooter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceFooterDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Services1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.SocialMedia", b =>
                {
                    b.Property<int>("SocialMediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialMediaId"));

                    b.Property<DateTime>("SocailMediaCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SocialMediaFacebookUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("SocialMediaInstagramUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("SocialMediaLinekdinUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("SocialMediaYoutubeUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("SocialMediaId");

                    b.HasIndex("SocialMediaId");

                    b.ToTable("SocialMedias1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<DateTime>("TeamCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamTitleHiglight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("Teams1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingId"));

                    b.Property<DateTime>("TrainingCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrainingDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainingTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainingId");

                    b.HasIndex("TrainingId");

                    b.ToTable("Trainings1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("UserCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UserIsAcTive")
                        .HasColumnType("bit");

                    b.Property<string>("UserPasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.Property<string>("UserUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.HasIndex("UserUserName")
                        .IsUnique();

                    b.ToTable("Users1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Value", b =>
                {
                    b.Property<int>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValueId"));

                    b.Property<DateTime>("ValueCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValueDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueFooterDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueFooterTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ValueId");

                    b.ToTable("Values1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Vision", b =>
                {
                    b.Property<int>("VisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisionId"));

                    b.Property<DateTime>("VisionCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisionSubDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisionId");

                    b.ToTable("Visions1", (string)null);
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Difficulty", b =>
                {
                    b.HasOne("SMConsulting.Core.Entities.SectorHelp", "SectorHelp")
                        .WithMany("Difficulties")
                        .HasForeignKey("DifficultSectorHelpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectorHelp");
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("SMConsulting.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("RefreshTokenUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.SectorHelp", b =>
                {
                    b.HasOne("SMConsulting.Core.Entities.Sector", "Sector")
                        .WithMany("SectorHelps")
                        .HasForeignKey("SectorHelpSectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.Sector", b =>
                {
                    b.Navigation("SectorHelps");
                });

            modelBuilder.Entity("SMConsulting.Core.Entities.SectorHelp", b =>
                {
                    b.Navigation("Difficulties");
                });
#pragma warning restore 612, 618
        }
    }
}
